### ISSUE TITLE
Elasticsearch Java High Level REST Client fixed to specific Elasticsearch major version

### ISSUE THREAD

**Issue by alxsap** [SAP/elasticsearch-logs-plugin#13]
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html

> It is recommended to **upgrade the High Level Client when upgrading the Elasticsearch cluster to a new major version**, as REST API breaking changes may cause unexpected results depending on the node that is hit by the request, and newly added APIs will only be supported by the newer version of the client. The client should always be updated last, once all of the nodes in the cluster have been upgraded to the new major version.

:warning: How shall we handle this in general? There will be only one latest version of this plugin,  with a specific Elasticsearch client version, working properly with a specific Elasticsearch major version. This means it might not work with older major versions of Elasticsearch and also not with newer ones.

**Comment by alxsap** [comment]
https://github.com/SAP/elasticsearch-logs-plugin/pull/12#issuecomment-540521008 from @mawinter69 
> Probably we use only a very small part of the offered API. If it works we might consider staying on the older version. In any case it must be clearly documented that a version mismatch is a potential problem.
As long as the java api is identical for the things we use we could extract the ES rest client into a separate jenkins plugin and then have versions for ES 6 and ES 7.
This would allow to run the plugin without changes with a fitting version. This of course raises the question who would maintain this additional plugin.

**Comment by alxsap** [comment]
@mawinter69 

#### Use older client version

> Probably we use only a very small part of the offered API. If it works we might consider staying on the older version. In any case it must be clearly documented that a version mismatch is a potential problem.

This would mean it works perfectly for an older version (6.x) and for the current version (7.x) we would have a disclaimer and it might potentially fail. Would be an option (as long as there are no effective known issues) but does not sound nice.

#### Jenkins plugin extensions providing different client versions

> As long as the java api is identical for the things we use we could extract the ES rest client into a separate jenkins plugin and then have versions for ES 6 and ES 7.

We also had this idea, but I doubt the API is identical. This would mean we would have to duplicate a generic ES client API in the Jenkins Extension. We could start only with the methods used by our plugin. But does not sound nice as well and will be quite some effort.
Maintaining a compatible client library is something I would expect from the Elasticsearch guys.

#### Maintain release branches with different plugin versions

A third option would be to maintain release branches for the different Elasticsearch major versions. Of course this will not work for the Jenkins Updatesite mechanism, but would work with binary references (e.g. curl into Docker image).
To work with Jenkins Updatesite we would have to introduce separate plugin identities, including packages 😩

**Comment by mawinter69** [comment]
I did not mean to create a special plugin with own code. Just a plugin that contains the original ES client jars and nothing else. Similar to the httpcomponents client plugin https://plugins.jenkins.io/apache-httpcomponents-client-4-api

**Comment by MichaelSp** [comment]
I'm currently too far away from the action. I'd like to leave this conversation/decision up to you

**Comment by alxsap** [comment]
> I did not mean to create a special plugin with own code. Just a plugin that contains the original ES client jars and nothing else. Similar to the [httpcomponents client plugin](https://plugins.jenkins.io/apache-httpcomponents-client-4-api)

We would need multiple versions of such a plugin (client 6.x, 7.x) and in our (single) Elasticsearch-logs-plugin we would need an option to switch between the installed client plugins, depending on the Elasticsearch server version.

The [httpcomponents](https://plugins.jenkins.io/apache-httpcomponents-client-4-api) way expects the consumer to have an explicit dependency to it. I think the idea is resource sharing and not use of multiple versions.

What we need is dependencies to multiple versions of the client (which does not work), or implemented as an Extension and a selection in the config, which version to use.

**Comment by mawinter69** [comment]
In our use case we will never talk to different ES instances at the same time.
The class loading of Jenkins will not allow to switch between installed plugins easily if possible at all.
We would do it identical to the way of http components. As we see in your pull request the java api of ES hasn't changed so we could run with 6 or 7. So we depend on 6, but if someone installs 7 we still run fine. The problem would be that Jenkins would offer plugin updates that should not be applied if ES is still on 6.

**Comment by anbrsap** [comment]
The current implementation doesn't use the Elasticsearch client library anymore.
